# Generated by Django 3.0.6 on 2020-06-03 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='content',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='board',
            name='title',
        ),
    ]
